### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by vdfbb** [cotag/condo_example#11]

**Comment by vdfbb** [comment]
Hi @stakach 
I am trying to use the code for uploading files to S3.
After finishing all procedures in 'Usage'. The following error message shows in the browser when open http://localhost:3000/
![image](https://user-images.githubusercontent.com/25852423/28639747-2b198094-7241-11e7-838f-3e4c4eac1483.png)

**Comment by stakach** [comment]
CoTag never actually used any server side rendering. As such the files were outdated and have been removed.

We are an AngularJS house and we have some AngularJS libraries that work with this API

We haven't quite completed our Angular2 library however it does work and can be found here: https://github.com/cotag/a2-uploads

The legacy Angular1 project will work with this example however the NPM dependencies are a little old and it may take some tweaking to run the development server. We currently use this library in production
https://github.com/cotag/angular-uploads

**Comment by stakach** [comment]
This project https://github.com/cotag/Condominios is the real server-side core

**Comment by vdfbb** [comment]
@stakach . Thanks for your reply. I havn't fully understood your answers.
The project https://github.com/cotag/condo_example is supposed to be an example of  https://github.com/cotag/Condominios, isn't it? 

The issue I got is with the example posted on https://github.com/cotag/condo_example, deployed it by following the procedures in 'Usage'. But got the following error message when open it in a browser:

![image](https://user-images.githubusercontent.com/25852423/28663684-f7bab388-72b5-11e7-8d59-9c400a2a058e.png)
